### ISSUE TITLE
Use browser action instead

### ISSUE THREAD

**Issue by Zirak** [Zirak/switcheroo#10]
Why didn't I think of this earlier?

Browser action popups don't depend on the surrounding page, and they execute in elevated privileges.

Downside: An icon will be needed.

**Comment by awalgarg** [comment]
this'd make it slow to start

also less portable to other browsers (_cough_ ff _cough_)

**Comment by Zirak** [comment]
Will check out slowness.
And FF doesn't need switcheroo, it's got this (and more!) in its own version of the omnibox. In this aspect it beats Chrome.

**Comment by Zirak** [comment]
It seems to work really well, better than the modal way. Give it a try, tell me if it's worse.
