### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Zirak** [Zirak/switcheroo#8]
![switcheroo-dark](https://cloud.githubusercontent.com/assets/1144615/9701333/642009e2-5413-11e5-81a2-76f817e1fd42.png)

How is it?

(cc @awalGarg)

**Comment by awalgarg** [comment]
GREEAT!

Except for that purplish highlight. Should be a grayish variant. Looks pretty good otherwise.

**Comment by Zirak** [comment]
http://jsbin.com/vesoculike/edit?css,output

I can't figure out a good gray colour; I took inspiration from several other modal menus, like some devtools themes, Sublime or Atom menus etc, and what I noticed is that on dark backgrounds, a coloured highlight was very neat.

Here're some colours I liked: http://hexpreview.com/(4E225E)(770E0E)(2A5390)

**Comment by awalgarg** [comment]
#615167 is from Predawn's file list highlight. See if you like it. Otherwise #4E225E (the first one in your hex list) is also good :)

**Comment by Zirak** [comment]
Solved by 73eeec7a079439c74f3e538727e3bb58a36a3ff5.
